# Generated by Django 5.2.8 on 2025-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrostation',
            name='station_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
