# Generated by Django 5.2.8 on 2025-11-15 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_metrostation_station_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataase',
            new_name='database',
        ),
    ]
