# Generated by Django 5.2.8 on 2025-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_rename_dataase_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='origin_staion',
            new_name='origin_station',
        ),
        migrations.RemoveField(
            model_name='database',
            name='user',
        ),
        migrations.AddField(
            model_name='database',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
