# Generated by Django 5.2.8 on 2025-11-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_origin_staion_database_origin_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='balance',
        ),
    ]
