# Generated by Django 5.2.8 on 2025-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='destination_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='database',
            name='origin_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
