# Generated by Django 5.2.8 on 2025-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticketscanner_database_destination_scanned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='ticket_status',
            field=models.CharField(default='Not Used', max_length=100),
        ),
    ]
