# Generated by Django 5.2.8 on 2025-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_database_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='timestamp',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
