# Generated by Django 5.2.8 on 2025-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_database_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
