# Generated by Django 5.2.8 on 2025-11-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_database_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('footfall', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TicketScanner',
        ),
    ]
