# Generated by Django 5.2.8 on 2025-11-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_footfall_delete_ticketscanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
