# Generated by Django 5.2.8 on 2025-11-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_systemtoggle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footfall',
            name='date',
        ),
        migrations.RemoveField(
            model_name='systemtoggle',
            name='date',
        ),
    ]
