# Generated by Django 5.2.8 on 2025-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_remove_footfall_date_remove_systemtoggle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtoggle',
            name='balance_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemtoggle',
            name='book_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemtoggle',
            name='scan_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemtoggle',
            name='view_status',
            field=models.BooleanField(default=True),
        ),
    ]
