# Generated by Django 5.2.8 on 2025-11-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_systemtoggle_balance_status_systemtoggle_book_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
                ('otp_generated', models.IntegerField()),
                ('time_at_otp_generated', models.DateTimeField()),
                ('origin_station_id', models.CharField(max_length=100)),
                ('destination_station_id', models.CharField(max_length=100)),
                ('fare', models.IntegerField()),
            ],
        ),
    ]
