# Generated by Django 5.2.8 on 2025-11-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_otp_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_verification',
            name='otp_generated',
            field=models.CharField(max_length=100),
        ),
    ]
