# Generated by Django 5.2.8 on 2025-11-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_alter_otp_verification_otp_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('connected_station', models.CharField(max_length=100)),
            ],
        ),
    ]
