# Generated by Django 5.2.8 on 2025-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_stationconnections'),
    ]

    operations = [
        migrations.AddField(
            model_name='footfall',
            name='date',
            field=models.DateField(default="2024-01-01"),
        ),

        migrations.AddField(
            model_name='systemtoggle',
            name='line_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemtoggle',
            name='line_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemtoggle',
            name='line_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemtoggle',
            name='line_4',
            field=models.BooleanField(default=True),
        ),
    ]
